var assert = require('assert')
var primeCalculator = require('../lib/prime')
var expect = require('expect.js')
  
before(function(){
  this.isPrime = function isPrime1(n) {
     if (isNaN(n) || !isFinite(n) || n%1 || n<2) return false; 
     var m=Math.sqrt(n);
     for (var i=2;i<=m;i++) if (n%i==0) return false;
     return true;
    }
})

suite('Prime Calculator', function() {
  test('should return equal number of primes to the passwd parameter', function(){
    var pc = new primeCalculator()
    var primes = pc.calculate(1000)
    expect(primes.length).to.be(1000)
  })
  
  test('All prime numbers generated by pc should be prime', function() {
    var pc = new primeCalculator()
    var primes = pc.calculate(1000)
    
    for(var i=0; i<primes.length; i++) {
      var prime = primes[i];
      
      assert.equal(this.isPrime(prime), true)
    }
  });
});