var assert = require('assert')
var numToWordsPrinter = require('../lib/printer')
var expect = require('expect.js')
  
before(function(){
  this.printer = new numToWordsPrinter()
  
  this.hashes = {
    
  }
})

suite('Prime Calculator', function() {
  test('should return equal number of primes to the passwd parameter', function(){
    var primes = this.pc.calculate(1000)
    expect(primes.length).to.be(1000)
  })
  
  test('All prime numbers generated by pc should be prime', function() {
    var primes = this.pc.calculate(1000)
    console.log(primes)
    
    for(var i=0; i<primes.length; i++) {
      var prime = primes[i];
      console.log(prime)
      assert.equal(this.isPrime(prime), true)
    }
  });
});